name: Build the portfolio website
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-portfolio-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: cd frontend && npm install

      - name: Build the project
        run: cd frontend && npm run build

  build-and-release-image:
    runs-on: ubuntu-latest
    needs: build-portfolio-website
    if: success()
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # all history for all branches and tags

      - name: Build and push Docker image
        env:
          REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        with:
          image: quay.io/podman/stable
          options: --volumes-from=${{ env.JOB_CONTAINER_NAME }}
          run: |
            podman build -t "${REGISTRY}/my-portfolio:latest" .
            podman login -u "${USERNAME}" -p "${PASSWORD}" "${REGISTRY}"
            podman push "${REGISTRY}/my-portfolio:latest"
